# Generated by Django 4.2.4 on 2023-08-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
