# Generated by Django 4.2.4 on 2023-08-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_cartitems_cart_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
