# Generated by Django 4.2.4 on 2023-08-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_cartitems_product_alter_cartitems_user_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='user',
        ),
    ]
