# Generated by Django 4.2.4 on 2023-08-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_cartitems_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='just_user',
        ),
    ]
