# Generated by Django 4.2.4 on 2023-08-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_cart_just_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
