# Generated by Django 4.2.4 on 2023-08-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='oredered',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
